from controller.Version import VersionController
from controller.Metatrader import MetatraderLoginController, MetatraderTradeStartController, MetatraderTradeExitController, MetatraderDataController, Mt5LogController
from controller.ClaudeTrader import ClaudeTraderOrdemController

